<!DOCTYPE html>
<html lang="en-MY">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @include('components.brand-head')
    <meta name="description" content="@yield('description')">
    <link rel="canonical" href="{{ url()->current() }}">
    <meta name="robots" content="index, follow">
    <title>@yield('title')</title>
    <style>
        :root{--navy:#12395d;--deep:#092b49;--teal:#319da2;--aqua:#91c6d0;--ice:#f3f8f9;--mist:#e5f1f3;--ink:#263640;--muted:#60737d;--line:#d4e3e6;--white:#fff;--shadow:0 16px 40px rgba(18,57,93,.09)}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);font:16px/1.7 Inter,system-ui,-apple-system,"Segoe UI",sans-serif}a{color:inherit;text-decoration:none}.container{width:min(1120px,calc(100% - 40px));margin:auto}.skip{position:fixed;top:-60px;left:16px;z-index:100;padding:10px 16px;background:var(--deep);color:#fff}.skip:focus{top:16px}
        header{position:sticky;top:0;z-index:30;background:rgba(255,255,255,.97);border-bottom:1px solid var(--line)}.nav{min-height:82px;display:flex;align-items:center;justify-content:space-between;gap:30px}.brand{display:flex;align-items:center;gap:11px;color:var(--navy);font-weight:850;letter-spacing:.07em}.mark{width:55px;height:55px;object-fit:contain}.brand em{color:var(--teal);font-style:normal}.brand small{display:block;color:var(--muted);font-size:9px;letter-spacing:.13em;text-transform:uppercase}.links{display:flex;align-items:center;gap:20px;color:var(--navy);font-size:13px;font-weight:750}.links a:hover,.links a[aria-current="page"]{color:var(--teal)}.nav-cta{padding:10px 15px;border-radius:5px;background:var(--teal);color:#fff!important}.menu{display:none;width:44px;height:44px;border:1px solid var(--line);background:#fff;color:var(--navy);font-size:19px}
        .crumb{padding:22px 0;color:var(--muted);font-size:13px}.crumb span{padding:0 9px}.hero{padding:72px 0 82px;background:linear-gradient(112deg,var(--ice),#fff 75%);border-bottom:1px solid var(--line)}.eyebrow{display:flex;align-items:center;gap:10px;margin:0 0 18px;color:var(--teal);font-size:12px;font-weight:850;letter-spacing:.14em;text-transform:uppercase}.eyebrow:before{content:"";width:28px;height:2px;background:currentColor}h1{max-width:850px;margin:0;color:var(--deep);font-size:clamp(43px,6vw,68px);line-height:1.05;letter-spacing:-.045em}.lead{max-width:820px;margin:24px 0 0;color:#506772;font-size:19px}
        .content{width:min(840px,100%);padding:72px 0 88px}.article{font-size:17px;color:var(--muted)}.article h2{margin:55px 0 17px;padding-top:4px;color:var(--deep);font-size:clamp(28px,4vw,40px);line-height:1.16;letter-spacing:-.025em}.article h3{margin:31px 0 12px;color:var(--navy);font-size:20px}.article p,.article ul,.article blockquote{margin:0 0 20px}.article ul{padding-left:24px}.article li{margin:8px 0}.article blockquote{padding:21px 24px;border-left:4px solid var(--teal);background:var(--mist);color:var(--navy);font-weight:700}.article strong{color:var(--navy)}.article a{display:inline-flex;margin:5px 8px 8px 0;padding:11px 17px;border:1px solid var(--teal);border-radius:5px;background:var(--teal);color:#fff;font-size:14px;font-weight:800}.article a:hover{background:#278b90}.article span[id]{scroll-margin-top:110px}
        .next{padding:70px 0;background:var(--ice)}.next h2{margin:0 0 28px;color:var(--deep);font-size:34px}.page-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.page-card{padding:23px;border:1px solid var(--line);background:#fff;color:var(--navy);font-weight:800}.page-card:hover{border-color:var(--teal);color:var(--teal)}
        .boundary{padding:30px 0;background:var(--navy);color:#d3e1e7}.boundary strong{color:#fff}footer{padding:48px 0 24px;background:var(--deep);color:#b9cbd4}.foot{display:flex;align-items:flex-start;justify-content:space-between;gap:40px}.foot nav{display:flex;flex-wrap:wrap;gap:18px;font-size:13px}.disclaimer{margin-top:34px;padding-top:22px;border-top:1px solid rgba(255,255,255,.13);font-size:12px}
        @media(max-width:900px){.menu{display:block}.links{display:none;position:absolute;inset:82px 0 auto;padding:24px;background:#fff;border-bottom:1px solid var(--line);flex-direction:column;align-items:stretch}.links.open{display:flex}.page-grid{grid-template-columns:1fr 1fr}}
        @media(max-width:620px){.container{width:min(100% - 28px,1120px)}.hero{padding:50px 0 62px}h1{font-size:42px}.content{padding:52px 0 68px}.page-grid{grid-template-columns:1fr}.foot{flex-direction:column}}
    </style>
    @stack('head')
</head>
<body>
<a class="skip" href="#main">Skip to main content</a>
<header><div class="container nav"><a class="brand" href="/joint-petition" aria-label="LegalDIY Joint Petition Knowledge Centre"><img class="mark" src="/images/legaldiy-mark.png" alt="" width="55" height="55"><span>LEGAL <em>DIY</em><small>Joint Petition Knowledge Centre</small></span></a><button class="menu" type="button" aria-label="Open navigation" aria-expanded="false">&#9776;</button><nav class="links" aria-label="Primary navigation"><a href="/joint-petition">Joint Petition</a><a href="/joint-petition/what-we-need-to-agree">What to Agree</a><a href="/joint-petition/why-agreement-matters">Why Agreement Matters</a><a href="/joint-petition/not-suitable">When It May Not Fit</a><a class="nav-cta" href="/joint-petition/readiness">Check Readiness</a></nav></div></header>
<main id="main">@yield('content')</main>
<section class="boundary"><div class="container"><strong>LegalDIY's current divorce pathway focuses on agreed Joint Petition matters.</strong> If you cannot proceed together or require a contested process, consider obtaining independent professional advice.</div></section>
<footer><div class="container"><div class="foot"><a class="brand" href="/joint-petition"><img class="mark" src="/images/legaldiy-mark.png" alt="" width="55" height="55"><span>LEGAL <em>DIY</em><small>Joint Petition Knowledge Centre</small></span></a><nav><a href="/joint-petition">Start</a><a href="/joint-petition/readiness">Readiness</a><a href="/joint-petition/what-we-need-to-agree">What to Agree</a><a href="/joint-petition/not-suitable">Not Suitable</a></nav></div><div class="disclaimer">LegalDIY provides general legal education and self-help information about civil divorce in Malaysia. LegalDIY is not a law firm. This information is not legal advice for an individual's circumstances.</div></div></footer>
<script>const b=document.querySelector('.menu'),n=document.querySelector('.links');b.addEventListener('click',()=>{const open=n.classList.toggle('open');b.setAttribute('aria-expanded',open)});</script>
</body>
</html>
