<?php

return [
    ['slug' => 'index', 'url' => '/joint-divorce', 'title' => 'Thinking About Divorcing Together?', 'seo' => 'Joint Petition Divorce in Malaysia | LegalDIY', 'description' => 'Thinking about divorcing together? Understand whether Joint Petition may be suitable and what you and your spouse need to decide.'],
    ['slug' => 'suitability', 'url' => '/joint-divorce/suitability', 'title' => 'Can We Divorce Together?', 'seo' => 'Can We Divorce Together by Joint Petition? | LegalDIY', 'description' => 'Start with the questions that help spouses understand whether they may be able to approach a Malaysian civil divorce together.'],
    ['slug' => 'joint-petition', 'url' => '/joint-divorce/joint-petition', 'title' => 'What Is a Joint Petition Divorce?', 'seo' => 'What Is a Joint Petition Divorce in Malaysia? | LegalDIY', 'description' => 'Understand what Joint Petition means when both spouses approach a civil divorce together in Malaysia.'],
    ['slug' => 'decisions', 'url' => '/joint-divorce/decisions', 'title' => 'What Do We Need to Agree On?', 'seo' => 'What Must Spouses Agree for a Joint Petition? | LegalDIY', 'description' => 'Understand the decisions spouses should work through about children, maintenance, property and their agreement.'],
    ['slug' => 'children', 'url' => '/joint-divorce/children', 'title' => 'Children: What Do We Need to Decide Together?', 'seo' => 'Children Arrangements in a Joint Petition Divorce | LegalDIY', 'description' => 'Work through children arrangements that cooperative parents should understand before a Joint Petition divorce.'],
    ['slug' => 'maintenance', 'url' => '/joint-divorce/maintenance', 'title' => 'Maintenance: What Do We Need to Decide Together?', 'seo' => 'Maintenance in a Joint Petition Divorce Malaysia | LegalDIY', 'description' => 'Understand child and spousal maintenance questions couples should discuss for an agreed Joint Petition divorce.'],
    ['slug' => 'property', 'url' => '/joint-divorce/property', 'title' => 'Property: What Do We Need to Decide Together?', 'seo' => 'Property in a Joint Petition Divorce Malaysia | LegalDIY', 'description' => 'Identify property, debts and practical arrangements spouses should understand before proceeding together.'],
    ['slug' => 'agreement', 'url' => '/joint-divorce/agreement', 'title' => 'Do You Really Have an Agreement?', 'seo' => 'Do We Have a Genuine Joint Petition Agreement? | LegalDIY', 'description' => 'Check whether your proposed Joint Petition arrangements are clear, informed, practical and voluntary.'],
    ['slug' => 'readiness', 'url' => '/joint-divorce/readiness', 'title' => 'Are We Ready to Proceed Together?', 'seo' => 'Joint Petition Divorce Readiness Check | LegalDIY', 'description' => 'Use a public educational checklist to identify which Joint Petition decisions are resolved and which need more thought.'],
    ['slug' => 'process', 'url' => '/joint-divorce/process', 'title' => 'How Does a Joint Petition Divorce Work?', 'seo' => 'Joint Petition Divorce Process in Malaysia | LegalDIY', 'description' => 'Understand the general stages of a Joint Petition civil divorce in Malaysia without private document-preparation instructions.'],
    ['slug' => 'court', 'url' => '/joint-divorce/court', 'title' => 'What Happens at Court in a Joint Petition Divorce?', 'seo' => 'Joint Petition Divorce Court in Malaysia | LegalDIY', 'description' => 'Understand the court role and what spouses should understand before a Joint Petition divorce hearing.'],
    ['slug' => 'finalisation', 'url' => '/joint-divorce/finalisation', 'title' => 'When Is Our Divorce Final?', 'seo' => 'When Is a Joint Petition Divorce Final in Malaysia? | LegalDIY', 'description' => 'Understand the Decree Nisi, Decree Nisi Absolute and updating divorce information with JPN.'],
    ['slug' => 'not-suitable', 'url' => '/joint-divorce/not-suitable', 'title' => 'When Joint Petition May Not Be Suitable', 'seo' => 'When Joint Petition May Not Be Suitable | LegalDIY', 'description' => 'Recognise circumstances where spouses may not currently be able to proceed together through LegalDIY’s Joint Petition pathway.'],
];
