<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class KnowledgeController extends Controller
{
    public function show(string $guide): View
    {
        if ($guide === 'children-maintenance') return view('knowledge.children-maintenance');
        $guides = $this->guides();
        abort_unless(isset($guides[$guide]), 404);
        return view('knowledge.show', ['guide' => $guides[$guide], 'slug' => $guide]);
    }

    public function examples(string $guide): View
    {
        $guides = $this->guides();
        abort_unless(isset($guides[$guide]), 404);
        return view('knowledge.examples', ['guide' => $guides[$guide], 'slug' => $guide]);
    }

    private function guides(): array
    {
        return [
            'property' => [
                'eyebrow' => 'Property',
                'scope' => 'This guide explains matrimonial assets under Part VII of Malaysia’s Law Reform (Marriage and Divorce) Act 1976 (Act 164), principally for civil, non-Muslim marriages.',
                'labels' => ['What counts', 'Asset picture', 'Contributions', 'Court factors', 'Outcomes', 'Agreement check'],
                'steps' => [
                    $this->step('What may count as a matrimonial asset?', 'Begin with assets acquired during the marriage—not only assets registered in both names.', [['Assets during marriage', 'The home, other property, savings, investments, vehicles, businesses, and other assets may need to be identified.'], ['Pre-marriage assets', 'An asset owned before marriage may enter the inquiry where it was substantially improved during marriage by the other spouse or their joint efforts.'], ['Title is not the whole answer', 'Registration in one spouse’s name does not, by itself, settle whether an asset is matrimonial or how it should be divided.'], ['Complex ownership', 'Inheritance, gifts, company interests, overseas assets, or disputed ownership may require individual legal and tax advice.']], 'Section 76(1) and (5)', 'Section 76 empowers the Court, when granting divorce or judicial separation, to divide matrimonial assets or order their sale. Subsection (5) addresses certain pre-marriage assets substantially improved during the marriage.'),
                    $this->step('Build a complete asset picture', 'A useful discussion begins with disclosure, current values, and obligations attached to each asset.', [['Create one list', 'Record each asset, legal owner, acquisition date, estimated current value, and available documents.'], ['Financing and debts', 'Identify borrowers, outstanding balances, instalments, arrears, and refinancing or consent needed.'], ['Use evidence', 'Gather titles, agreements, statements, valuations, company records, and proof of major improvements.'], ['Compare like with like', 'Agree on a valuation date and method. A professional valuation may be necessary.']], 'Section 76', 'The statutory assessment depends on evidence about assets, contributions, relevant debts, children’s needs, and duration of marriage.'),
                    $this->step('Understand different contributions', 'Contribution is wider than the name on a payment receipt.', [['Money and property', 'Deposits, instalments, renovations, capital, and property contributed to acquisition or improvement may be relevant.'], ['Work toward an asset', 'Work performed in acquiring, preserving, or developing an asset or business may be relevant.'], ['Family and home work', 'Caring for children, managing the home, and paying family expenses must not be treated as having no value.'], ['Keep a chronology', 'Record when contributions were made and whether they related to assets, family expenses, debt, or improvement.']], 'Section 76(2)(a)', 'The current section 76 directs the Court to consider contributions in money, property, or work toward acquiring assets or paying expenses for the family’s benefit.'),
                    $this->step('What else does the Court consider?', 'Division is not produced by a universal percentage or calculator.', [['Joint-benefit debts', 'The Court may consider debts incurred by either spouse for their joint benefit.'], ['Minor children’s needs', 'Housing and other needs of minor children may affect a practical arrangement.'], ['Duration', 'The length of the marriage is a statutory consideration.'], ['Inclination towards equality', 'After considering the factors, section 76 directs the Court to incline towards equality. This is not a promise of an automatic 50/50 result in every dispute.']], 'Section 76(2)', 'Section 76 lists contributions, joint-benefit debts, minor children’s needs, and marriage duration, and directs the Court to incline towards equality.'),
                    $this->step('Explore workable outcomes', 'A percentage is only one part of a complete property arrangement.', [['One spouse keeps it', 'Consider valuation, payment, financing, lender consent, transfer costs, and deadlines.'], ['Sell and divide', 'Define sale decisions, occupancy, expenses, redemption, and division of net proceeds.'], ['Offset another asset', 'One asset may be retained for another asset or payment, but values, liquidity, tax, and enforceability matter.'], ['Implementation', 'A proposed transfer does not itself release a borrower or complete registration. External approvals may be necessary.']], 'Section 76(1)', 'The Court may order division of assets or their sale and division of proceeds. The implementation mechanism should be clear.'),
                    $this->step('Is the property arrangement ready?', 'Test whether both spouses understand the assets and how the outcome will be completed.', [['Disclosure', 'Have all material assets, values, interests, and relevant debts been disclosed?'], ['Clear terms', 'Is it clear who keeps what, what is paid, how net proceeds are calculated, and when?'], ['Feasibility', 'Can the financing, transfer, sale, or payment actually be completed?'], ['Unresolved risk', 'Hidden assets, business values, overseas property, bankruptcy, or disposal risks may need tailored advice.']], 'Sections 76 and 52', 'For a joint petition, arrangements should be complete enough for free consent and for the Court to consider the provision made on dissolution.'),
                ],
                'story_title' => 'Property stories from different marriages.',
                'stories' => [['Grace and Jonathan value the family home', 'Grace will remain with their child. They obtain a valuation, confirm the loan, test refinancing, and specify payment and transfer deadlines.', 'What is the net value? What happens if financing is refused?'], ['Sofia and Marcus decide to sell', 'Neither can sustainably keep the property. They agree on the agent, sale decisions, costs, and division of net proceeds.', 'Who manages the sale? Which costs come out first?'], ['Aisha and Peter recognise unpaid work', 'Peter paid most instalments while Aisha reduced paid work to care for the family. They record financial and family contributions.', 'What money, property, work, and family contributions were made?'], ['Elena and Christopher face a business dispute', 'Incomplete company records and disagreement over value prevent settlement, so they obtain tailored advice.', 'Is value disputed? Are records missing?']],
            ],
            'alimony' => [
                'eyebrow' => 'Alimony & spousal maintenance',
                'scope' => 'This guide explains maintenance between spouses under Part VII of Act 164, principally for civil, non-Muslim marriages.',
                'labels' => ['Meaning', 'Who may claim', 'Means & needs', 'Payment design', 'Duration', 'Changes'],
                'steps' => [
                    $this->step('What is spousal maintenance?', 'Spousal maintenance—sometimes called alimony—is financial support between spouses or former spouses.', [['Separate question', 'It is separate from child maintenance and matrimonial asset division.'], ['Not automatic', 'Divorce does not automatically produce maintenance at a fixed amount or duration.'], ['When it may arise', 'Section 77 gives the Court powers during proceedings and when granting or after a relevant decree.'], ['Start with evidence', 'Income, resources, expenses, health, work circumstances, and existing support matter.']], 'Section 77', 'Section 77 describes when the Court may order maintenance during proceedings and when granting or after divorce or judicial separation.'),
                    $this->step('Who can be ordered to pay?', 'The statutory wording is gender-specific and should be explained accurately.', [['Wife or former wife', 'Section 77 empowers the Court to order a man to pay maintenance to his wife or former wife.'], ['Corresponding power', 'A woman may be ordered to pay where a husband or former husband is wholly or partly incapacitated from earning by injury or ill-health and an order is reasonable having regard to her means.'], ['No shortcut', 'Do not assume every wife receives maintenance or that both spouses always pay equally.'], ['Children are separate', 'Personal support between spouses should be separated from child expenses.']], 'Section 77(1)–(2)', 'Section 77 states the Court’s powers and the circumstances for the corresponding power concerning an incapacitated husband or former husband.'),
                    $this->step('How is maintenance assessed?', 'The Act does not prescribe a salary percentage or universal figure.', [['Means', 'Consider income, assets, earning ability, liabilities, and available resources.'], ['Needs', 'Identify reasonable personal needs and distinguish children’s expenses.'], ['Responsibility', 'Section 78 also directs consideration of responsibility apportioned for the breakdown.'], ['No income-ratio formula', 'Assessment is primarily based on means and needs regardless of the amount’s proportion to income.']], 'Section 78', 'Section 78 bases assessment primarily on means and needs and requires regard to responsibility apportioned for the marriage breakdown.'),
                    $this->step('How can payment be structured?', 'Amount, method, timing, and enforceability should work together.', [['Periodic payments', 'Record amount, first date, due day, method, duration, and review.'], ['Capital settlement', 'A capital settlement of all future maintenance claims is not effective under section 80 until Court approval.'], ['Security', 'Section 79 permits the Court, in its discretion, to secure maintenance through property held on trust.'], ['Avoid vague terms', 'State amount, frequency, start date, and intended duration.']], 'Sections 79 and 80', 'Section 79 concerns security. Section 80 requires Court approval for an agreed capital settlement of all future claims.'),
                    $this->step('How long can maintenance continue?', 'Duration depends on the order or approved arrangement and statutory ending rules.', [['Shorter period', 'An order may expressly run for a shorter period or be rescinded.'], ['Unsecured order', 'Subject to section 82, it expires on the death of either spouse, whichever occurs first.'], ['Secured order', 'Subject to section 82, it expires on the death of the spouse in whose favour it was made.'], ['Remarriage', 'Section 82 contains rules on remarriage and “living in adultery”; an agreement must also be read by its terms.']], 'Sections 81 and 82', 'Sections 81 and 82 govern duration and cessation. Read the particular order or agreement together with the statute.'),
                    $this->step('Can maintenance be changed?', 'A changed circumstance does not automatically rewrite an existing order.', [['Orders', 'An order may be varied or rescinded for misrepresentation, mistake of fact, or material change.'], ['Agreements', 'Subject to section 80, the Court may vary a maintenance agreement after a material change.'], ['Evidence', 'Income reduction, retirement, illness, or increased need should be supported.'], ['Proper process', 'Do not simply stop complying because circumstances changed.']], 'Sections 83 and 84', 'Sections 83 and 84 provide mechanisms for varying orders and agreements. Section 84 requires a material—not merely minor—change.'),
                ],
                'story_title' => 'Spousal maintenance stories from different marriages.',
                'stories' => [['Claire and Benjamin plan transitional support', 'They list needs, means, a monthly amount, payment date, and review point while Claire retrains.', 'What is reasonably needed and affordable?'], ['Natalie and George agree no spousal payment', 'Both can meet personal needs after full disclosure. They address children and property separately.', 'Are all separate financial questions addressed?'], ['Olivia and Samuel consider a capital settlement', 'They discuss a capital sum and learn why Court approval under section 80 matters.', 'What is settled and are the consequences understood?'], ['Isabella and Andrew face changed circumstances', 'An order remains in place when income falls. They gather evidence and use the variation process.', 'What remains payable until variation?']],
            ],
            'joint-petition' => [
                'eyebrow' => 'Joint petition & court process',
                'scope' => 'This guide explains dissolution by mutual consent under Act 164, principally for civil, non-Muslim marriages. Current Court and registry requirements must be checked.',
                'labels' => ['Mutual consent', 'Two-year rule', 'Full agreement', 'Documents', 'Court stage', 'Finalisation'],
                'steps' => [
                    $this->step('What makes a joint petition joint?', 'Both spouses ask the Court together to dissolve the marriage and must freely consent.', [['Shared application', 'Both spouses participate; it is not one spouse filing allegations against the other.'], ['Free consent', 'Pressure, misunderstanding, or unresolved terms undermine the foundation.'], ['The Court decides', 'Agreement does not privately dissolve the marriage or remove the Court’s role.'], ['A distinct route', 'The general reconciliation-body requirement does not apply in the same way to mutual consent.']], 'Sections 52 and 106', 'Section 52 permits a joint petition where spouses mutually agree and freely consent. Section 106 treats mutual consent as an exception to its general reconciliation-body requirement.'),
                    $this->step('The first two years of marriage', 'A joint petition is generally presented only after two years from the marriage date.', [['Use the legal date', 'Use the marriage date on the certificate, not the separation date.'], ['Exceptional leave', 'Section 50 permits an earlier petition only for exceptional circumstances or hardship.'], ['Court conditions', 'The Court may impose conditions and considers children and prospects of reconciliation.'], ['Do not assume an exception', 'A couple within two years should obtain advice before an ordinary filing.']], 'Sections 50 and 52', 'Section 52 states the two-year period. Section 50 contains a limited judicial power to permit an earlier petition.'),
                    $this->step('Agreement must cover the real issues', 'Agreeing to divorce is not the same as having complete terms.', [['Children', 'Address custody, care, access, maintenance, travel, and relocation where relevant.'], ['Property', 'Identify assets and debts and explain retention, transfer, sale, proceeds, and implementation.'], ['Spousal maintenance', 'State whether support is proposed and its amount, form, timing, and duration.'], ['Other terms', 'Costs, documents, deadlines, and dependent obligations should be clear.']], 'Section 52', 'The Court must be satisfied that proper provision is made for the wife and for children’s support, care, and custody, if any, and may attach conditions.'),
                    $this->step('Prepare and review the petition', 'The document must tell one accurate story and record the agreed relief.', [['Official records', 'Check names, identity details, marriage particulars, addresses, and children’s details.'], ['Precise terms', 'Match each term to the right person, amount, asset, and date.'], ['Read before signing', 'Each spouse should understand the complete petition and remove blanks or unintended terms.'], ['Formalities', 'Follow current Court requirements for signing, affirmation, exhibits, filing, and fees.']], 'Sections 52 and 57', 'Section 57 identifies matters ordinarily stated in a divorce petition, including maintenance, children, and property. Section 52 governs mutual consent.'),
                    $this->step('What happens at Court?', 'Filing begins the Court process; it is not itself the final divorce.', [['Registry stage', 'Documents may need correction or additional material.'], ['Hearing', 'The Court may ask both spouses about consent and arrangements. Confirm attendance requirements.'], ['Judicial scrutiny', 'The judge may allow, adjourn, decline, or attach conditions.'], ['Decree nisi', 'If allowed, the Court first makes a decree nisi; it is not ordinarily absolute immediately.']], 'Sections 52 and 61', 'Section 52 preserves the Court’s role. Section 61 provides the general decree nisi and decree absolute framework.'),
                    $this->step('Finalisation and records', 'Complete post-hearing steps and keep final documents safely.', [['Decree absolute', 'The marriage is not finally dissolved merely because the hearing occurred.'], ['Three-month framework', 'Section 61 generally allows a decree nisi to be made absolute after three months, subject to the Court’s powers.'], ['Registration and updates', 'Complete required registration or notification and update relevant records.'], ['Implement orders', 'Transfers, payments, and child arrangements may continue after finalisation.']], 'Sections 61 and 107', 'Section 61 addresses finalisation. Section 107 concerns registration of divorces and annulments. Confirm current procedural requirements.'),
                ],
                'story_title' => 'Joint-petition stories from different marriages.',
                'stories' => [['Victoria and Henry have a simple agreement', 'They verify their records, review the complete petition, and attend the Court stage.', 'Do both freely consent? Is anything overlooked?'], ['Maya and William clarify parenting terms', 'They replace vague “reasonable access” with workable school, holiday, transport, and expense terms.', 'Are all child arrangements clear?'], ['Chloe and Alexander coordinate property steps', 'Their terms include value, payment, lender approval, deadlines, and a refinancing fallback.', 'Can the order actually be implemented?'], ['Emma and Lucas are not fully agreed yet', 'They dispute relocation and a business value, so they obtain help instead of presenting completed terms.', 'Do unresolved issues make this route unsuitable for now?']],
            ],
        ];
    }

    private function step(string $title, string $intro, array $cards, string $reference, string $law): array
    {
        return compact('title', 'intro', 'cards', 'reference', 'law');
    }
}
